ports = [
    "sqlite3@3.49.0",
    "zlib@1.3.1",
    "opencv@4.11.0"
]

vars = [
    "VAR1=value1",
    "VAR2=value2"
]

envs = [
    "ENV_VAR1=/home/ubuntu/ccache",
    "LLVM_CONFIG=${LLVM_CONFIG}",
]

micros = [
    "MICRO_VAR1=111",
    "MICRO_VAR2"
]

flags = [
    "-Wall",
    "-Wno-unused-variable",
    "-Wno-deprecated",
    "-Wl,--allow-shlib-undefined"
]