[toolchain]
  url = "https://github.com/celer-pkg/test-conf/releases/download/resource/qnx800.tar.xz"
  path = "qnx800/host/linux/x86_64/usr/bin"
  name = "qcc"
  version = "12.2.0"
  system_name = "qnx"
  system_processor = "aarch64"
  host = "aarch64-nto-qnx"
  crosstool_prefix = "ntoaarch64-"
  cc = "qcc"
  cxx = "q++"
  ld = "ntoaarch64-ld"
  ranlib = "ntoaarch64-ranlib"
  ar = "ntoaarch64-ar"
  nm = "ntoaarch64-nm"
  objdump = "ntoaarch64-objdump"
  strip = "ntoaarch64-strip"
  c_compiler_target = "gcc_ntoaarch64le"
  cxx_compiler_target = "gcc_ntoaarch64le_cxx"
  envs = [
    "QNX_HOST=${TOOLCHAIN_DIR}/host/linux/x86_64",
    "QNX_TARGET=${TOOLCHAIN_DIR}/target/qnx",
    "QNX_CONFIGURATION=${TOOLCHAIN_DIR}/.qnx",
    "QNX_CONFIGURATION_EXCLUSIVE=${TOOLCHAIN_DIR}/.qnx",
    "MAKEFLAGS=${TOOLCHAIN_DIR}/target/qnx/usr/include",
  ]
