[toolchain]
url = "file:///C:/Program Files/Microsoft Visual Studio/2022/Enterprise"
name = "msvc"
version = "14.44.35207"
system_name = "Windows"
system_processor = "x86_64"
host = "x86_64-w64-mingw32"