[rootfs]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/ubuntu-base-20.04.5-base-amd64.tar.gz"
path = "ubuntu-base-20.04.5-base-amd64"
pkg_config_path = [
    "usr/lib/x86_64-linux-gnu/pkgconfig",
    "usr/share/pkgconfig",
    "usr/lib/pkgconfig"
]

[toolchain]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/gcc-9.5.0.tar.gz"
path = "gcc-9.5.0/bin"
name = "gcc"
version = "9.5"
system_name = "Linux"
system_processor = "x86_64"
host = "x86_64-linux-gnu"
crosstool_prefix = "x86_64-linux-gnu-"
cc = "x86_64-linux-gnu-gcc"
cxx = "x86_64-linux-gnu-g++"
fc = "x86_64-linux-gnu-gfortran"
ranlib = "x86_64-linux-gnu-ranlib"
ar = "x86_64-linux-gnu-ar"
nm = "x86_64-linux-gnu-nm"
objdump = "x86_64-linux-gnu-objdump"
strip = "x86_64-linux-gnu-strip"
