[toolchain]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/gcc-11.5.0.tar.gz"
path = "gcc-11.5.0/bin"
name = "gcc"
version = "11.5.0"
system_name = "linux"
system_processor = "x86_64"
host = "x86_64-linux-gnu"
crosstool_prefix = "x86_64-linux-gnu-"
cc = "x86_64-linux-gnu-gcc"
cxx = "x86_64-linux-gnu-g++"

[rootfs]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/ubuntu-base-22.04.5-base-amd64.tar.xz"
path = "ubuntu-base-22.04.5-base-amd64"
pkg_config_path = ["usr/lib/x86_64-linux-gnu/pkgconfig"]
lib_dirs = ["lib/x86_64-linux-gnu", "usr/lib/x86_64-linux-gnu"]
