[package]
ref = "stable"

[[build_configs]]
pattern = "x86_64-linux*"
build_system = "prebuilt"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-x264@stable@x86_64-linux.tar.gz"

[[build_configs]]
pattern = "aarch64-linux*"
build_system = "prebuilt"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-x264@stable@aarch64-linux.tar.gz"

[[build_configs]]
pattern = "x86_64-windows*"
build_system = "prebuilt"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-x264@stable@x86_64-windows.tar.gz"