[package]
url = "https://ffmpeg.org/releases/ffmpeg-5.1.6.tar.xz"
ref = "5.1.6"

# ================ build for Linux ================ #
[[build_configs]]
system_name = "linux"
options = [
    "--sysroot=${SYSROOT}",
    "--cross-prefix=${CROSS_PREFIX}",
    "--arch=${SYSTEM_PROCESSOR}",
    "--target-os=linux",
    "--pkg-config=pkgconf",
    "--enable-cross-compile",
    "--disable-programs",
    "--disable-doc",
    "--enable-pic",
    "--enable-gpl",
    "--enable-libx264",
]
dev_dependencies = ["pkgconf@2.4.3", "nasm@2.16.03"]
dependencies = ["x264@stable"]

# ================ build for Windows ================ #
[[build_configs]]
system_name = "windows"
options = [
    "--toolchain=msvc",
    "--target-os=win64",
    "--pkg-config=pkgconf",
    "--disable-programs",
    "--disable-doc",
    "--enable-pic",
    "--enable-gpl",
    "--enable-libx264",
]
dev_dependencies = ["pkgconf@2.4.3", "nasm@2.16.03"]
dependencies = ["x264@stable"]
