[package]
ref = "stable"

[[build_configs]]
system_name = "linux"
system_processor = "x86_64"
build_system = "prebuilt"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-x264@stable@x86_64-linux.tar.gz"