[package]
ref = "5.1.6"

[[build_configs]]
system_name = "linux"
system_processor = "x86_64"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-ffmpeg@5.1.6@x86_64-linux.tar.gz"
build_system = "prebuilt"
library_type = "interface"

[[build_configs]]
system_name = "windows"
system_processor = "x86_64"
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/prebuilt-ffmpeg@5.1.6@x86_64-windows.tar.gz"
build_system = "prebuilt"
library_type = "interface"